const options = {
  animals: ['zoos','goats','rabbits','zoo','pets','reptiles','pigs','elephants','cruelty','foxes','monkeys','animal','humane','cows','deer','humans','hunted','cats','mammals','snakes','sheep','dogs','mice','rats','veterinary','insects','birds','predators','creatures','elephant','wolves','cattle','horses','livestock','wild','prey','organisms','pet','endangered','eat','fur','meat','hunting','breeding','feeding','breed','lions','wildlife','lion','extinct','eating','welfare','fish','bears','tiger','exhibit','cat','bear','species','dog','bird','food','tigers','habitat','farms'],
  sports: ['softball','netball','shooter','badminton','espn','volleyball','tennis','lacrosse','handball','swimming','gymnastics','skiing','basketball','commentator','soccer','varsity','athletes','equipment','sport','golf','athletics','sporting','rowing','fitness','captain','boxing','broadcaster','arena','indoor','baseball','cycling','athletic','uniforms','hockey','reporter','cricket','bowling','skating','diving','athlete','egos','recreation','rugby','olympic','stadium','football','clubs','complex','drugs','racing','outdoor','wrestling','olympics', 'venues','curling','nba','nfl','entertainment','ncaa'],
  literature: ['shakespeare','literary','poetry','linguistics','nobel','prose','poets','poe','wilde','goethe','poems','essays','humanities','authors','books','magazines','writings','translation','poet','journals','plays','fiction','publications','thesis','quotation','epic','bibliography','library','creative','language','languages','journals','books','culture','writing','criticism','edited','novel','chapters','poem','publishing'],
  emotions: ['sadness','emotion','disgust','affective','arousal','anger','empathy','emotional','facial','feelings','happiness','jealousy','expressions','shame','grief','anxiety','desires','thoughts','guilt','fear','joy','cognitive','hatred','mood','responses','rage','feeling','behavioral','sad','attitudes','negative','hate','memories','affect','perception','experiences','psychological','feel','pleasure','moral','behavior','self','expression','positive','relationships','intense','pain','mind','surprise','experienced','psychology','stress','humans','mental','brain','expressed','perceived','pride','cultures','love','felt','actions','experience','understand','thinking','faces','tend','personality','understanding','romantic','desire'],
  food: ['beverage','nutrition','foods','beverages','drink','cooked','poisoning','eaten','cooking','drinks','cuisine','vendors','dishes','meals','ingredients','snacks','eat','hunger','allergies','eating','meal','chef','vegetables','meat','oranges','consumed','cake','crops','diet','agriculture','restaurant','feeding','bread','processing','breakfast','dinner','chicken','lunch','consumption','groceries','brunch','wine','products','fruits','chocolate','stores','crop','feed','milk','kitchen','safety','waste','rice','dessert','healthy','fish','preparation','seeds','tacos','organic','fresh','agricultural','eggs','restaurants'],
  programming: ['lisp','class','python','javascript','api','html','compiler','syntax','css','sass','languages','programmer','react','angular','java','analog','language','interface','node','backend','frontend','scripting','boolean','string','array','object','oop','testing','algorithms','ide','dom','mysql','logic','query','arguments','functions','parameter','network','iterate','format','github','computing','ibm','apple','functional','algorithm','tech','ajax','software','computer','json','code','scratch','microworlds','implementation','hardware','applications']
}

// console.log(options.sports[10]);

module.exports = options;